apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: aks
spec:
  selector:
    matchLabels:
      app: aks
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: aks
    spec:
      containers:
      - name: aks
        image: amk8acr.azurecr.io/containerrepo:#{Build.BuildId}#
        ports:
        - containerPort: 4500
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        
---
kind: Service
apiVersion: v1
metadata:
  name: aks
spec:
  selector:
    app: aks
  ports:
  - protocol: TCP
    port: 4500
    targetPort: 4500
  type: LoadBalancer
